FLAGI=-g -pedantic -Wall -std=c++0x

program4: src/zad4.cpp
	g++ ${FLAGI} -o program4 src/zad4.cpp

program3: src/zad3.cpp
	g++ ${FLAGI} -o program3 src/zad3.cpp

program1: src/tabdyn.cpp
	g++ ${FLAGI} -o program1 src/tabdyn.cpp
